### ISSUE TITLE
PlatON技术与治理委员会第一次会议议题 

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/meeting#1]
## PlatON核心开发者 0 会议议题
- 会议时间：2021-02-02 14:00 ~ 16:00
- 会议方式：网络会议
- 与会人员：qujunjie lishenglin guowenjing biganxin jianghaitao

### 议题
1. 选举产生技术与治理委员会主席
2. 学习/讨论修改《技术与治理委员会工作制度》
3. 就委员会各角色职责、分工、工作流程以及考核&汇报制度等细节进一步讨论明确
4. 明确技术与治理委员会例会、月度会议流程

**Comment by jiangshangqifeng** [comment]
Closed in favor of #2
