### ISSUE TITLE
关于零出块和双签处罚的讨论 Proposal discussion:  adjustment of zero block produce and double-signing slash.

### ISSUE THREAD

**Issue by nodeasy** [PlatONnetwork/meeting#7]
提案背景：目前PlatON主网验证人数量已经达到200+个，相比于其他公链，PlatON的零出块处罚较大而双签处罚偏低，在遇到网络波动等情况下，短时间内会造成验证人自抵押金额的较大损失；综合公链安全和节点群中其他验证人的意见后，我们发起如下提案：
涉及相关的治理参数和我们建议的修改值如下：

Proposal background: At present, the number of PlatON mainnet validators has reached 200+. Compared with other Blockchains, the Zero Produce panalty of PlatON is too high and double-signing penalty is comparatively too low, which will cause a large loss of the validator's self-stakes when facing infrastructure problems; in the comprehensive of the chain's safty and  other validators' opinions, we initiated the following proposal:

The proposal parameters and our suggested changes values are as follows:

1. slashBlocksReward  (出块率为0，削减的块奖励数量)
当前值：2,500，建议修改：25
当前出块奖励约 4. 43 LAT，则零出块处罚为 2,500 * 4.43 = 11,075 LAT 约为节点最低自抵押的11%
修改后处罚为 25 * 4.43 = 110.75 LAT 约为最低自抵押的0.1%
slashBlocksReward  (Slash the number of block rewards(block rate=0%))
Current value: 2,500, Suggest changes: 25
The current block reward is about 4.43 LAT, Then the zero block penalty is 2,500 * 4.43 = 11,075 LAT. 11% of the node minimum self-delegate.
The revised penalty is 25 * 4.43 = 110.75 LAT, which is approximately 0.1% of the minimum self-delegate.

2. zeroProduceCumulativeTime（零出块持续的共识轮数，并在该时间内进行零出块次数的累计）
当前值：20，建议修改：50
20 轮共 430 * 20 = 8,600 秒 （约2.38小时），修改为 50 后约 5.97 小时
ZeroProduceCumulativeTime   (Penalty threshold: Maintaining the consensus round number of zero production blocks, and accumulate times)
Current value: 20, Suggest changes: 50
20 epoch total 430 * 20 = 8,600 seconds (~2.38 hours), ~5.97 hours after modification to 50.

3. zeroProduceNumberThreshold （零出块次数处罚阈值）
当前值：1，建议修改：2
Zero Produce Number Threshold (Penalty threshold: Number of zero production blocks.)
Current value: 1, Suggest changes: 2

4. zeroProduceFreezeDuration（节点零出块惩罚被锁定时间（一个结算周期10750blocks））
当前值：56（约7天），建议修改：8（约24小时）
zeroProduceFreezeDuration (The lock time of node zero out-block penalty (1 epoch=10750blocks))
Current value: 56 (~7 days), Suggest changes: 8 (~24 hours)

5. slashFractionDuplicateSign (双签举报处罚节点自有质押金比例(‱))
当前值：10，建议修改：2000
双签处罚从万10大幅提高到20%
slashFractionDuplicateSign (Slash ratio of DoubleSign(‱))
Current value: 10, Suggest changes: 2000
Double-sign increased 20‱ from 10‱

以上仅为节点易建议的治理参数阈值，希望大家踊跃提出建议，达成共识之后届时再发起提案
相关治理参数可见 [https://scan.platon.network/governable-parameter](https://scan.platon.network/governable-parameter)

The above are reasonable thresholds for governance parameters calculated by Nodeasy. We hope that everyone could make suggestions and initiate a proposal after reaching a consensus.
Related governance constants: [https://scan.platon.network/governable-parameter](https://scan.platon.network/governable-parameter)

**Comment by surper214586910** [comment]
为了节点整体的竞争活力和稳定，建议修改现运行的规则。
